# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bdd07fe636e2a8d15b4a560535f0570efbd9a57a0441b8474e10eb3259981c7e057e0639924969dd48b7cb86a4f662b179a5cd165ed8c1cc198f6c5d38052663

test:
  secret_key_base: 23ad651ac76f3278eb40ac9746613c72abb4b4301cdfbc89f7752b090e07d060e052c361353debfbe8739c082657e5773a3090224b0e8383f9fcc6ecc22efc33

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
